### PR TITLE
Automatically use ExUnit.Case' from 'use ShouldI'

### PR DESCRIPTION
**Pull request by lpil**
Hello!

My attempt to solve #7. This seems deceptively simple, which makes me think that I've probably done something wrong. The tests seem to be passing though!

What are your thoughts? :)

Cheers,
Louis

### CODE REVIEW

**Comment by ericmj** [comment]
Looks good but we also need to pass options to `ExUnit.Case`, in particular the `:async` option. See http://elixir-lang.org/docs/stable/ex_unit/ExUnit.Case.html.

**Comment by lpil** [comment]
Ah, I see. I'll see what I can do. :)

**Comment by lpil** [comment]
Hello again. I've made a change, but I'm not sure how to go about writing a test for this- or even how to verify that it's implemented correctly. Sorry, but could you offer any advice?

Thanks,
Louis

**Comment by ericmj** [comment]
Perfect! We don't need a test for that.

**Comment by lpil** [comment]
OK, thanks :)

**Pull request merged**
